### ISSUE TITLE
large set of mutations to A or T (or ambiguous) in some recent sequences - systematic error??

### ISSUE THREAD

**Issue by AngieHinrichs** [COG-UK/dipi-group#109]
Not sure if this is the right place to report odd mutations that might be due to systematic error, but even if it's not I hope you'll know the right folks to talk to.  I noticed (thanks to Theo Sanderson's https://cov2tree.org) this very long branch within B.1.617.2 (Delta) in UCSC's tree, leading to 254 sequences from England & Scotland with collection dates 2021-06-26 - 2021-07-01:

![image](https://user-images.githubusercontent.com/186983/126699513-422a80d4-0988-4c86-bb73-ae1f7fb1cd84.png)

Interactive view:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/longBranchInDelta.json?c=country

Sequence names and dates:
[longBranchInDelta.tsv.gz](https://github.com/COG-UK/dipi-group/files/6864801/longBranchInDelta.tsv.gz)

21 mutations on the long branch:
```
G1319T
T2698A
G3239A
G3947T
G6589T
G6660T
C6990A
G7469T
G10787A
A11537T
C13824A
G14071T
C15796A
G19078T
T22672A
G23885A
T23943A
T29148A
G29395T
G29414A
G29434T
```
@russcd pointed out that all of those are to A or T.  Only one sequence splits at the end of that branch, followed by C4237T,C17040T,A19162G: all back-mutations to reference, probably a symptom of where the long branch happened to be placed based on which sequence usher placed first.  The next branch adds T6023A and another back-mut to ref, T20357G.
There are several other branches with lots of descendants within that subtree that have multiple mutations to A or T.

Since the mutations are spread across the genome, we don't think this looks like recombination.  The large set of mutations to A or T, the narrow range of dates, and the divergence within the 254 sequences are all sus.  Any ideas?  Thanks!

**Comment by rambaut** [comment]
I will look into this. Thanks

**Comment by rambaut** [comment]
The internal branches of the cluster seems to contain many of the same mutations occurring as if homoplasy

**Comment by rambaut** [comment]
But I think they are then flipping back at the tips. Could this be something to do with Augur's ancestral reconstruction?

**Comment by rambaut** [comment]
Have they changed how Augur deals with ambiguities or anything recently?

**Comment by AngieHinrichs** [comment]
That's a Nextstrain view of the UCSC tree constructed by usher, not Augur.  (The JSON that nextstrain is displaying is the output of the usher web interface, https://genome.ucsc.edu/cgi-bin/hgPhyloPlace, after increasing the tree size to 1000 and pasting in the ID of the first sequence in that cluster, England/ALDP-182C6B6/2021.)

**Comment by rambaut** [comment]
OK - is it an issue with usher's reconstuction then? Is it putting a bunch of spurious mutations on and then having to undo them in the stem branch?

**Comment by rambaut** [comment]
Easy thing to try - make an ML tree of the set of genomes in the tree above.

**Comment by AngieHinrichs** [comment]
I will take a closer look at the sequences to see whether they all have those 21 odd mutations (or at least most of them).  I expect that having such a long branch would prevent that from being a parsimonious placement for most sequences, but I guess something could be going wrong in there and causing back-mutations to accumulate.  I'll take a closer look at the mutations in that branch too.

**Comment by AngieHinrichs** [comment]
It's definitely the first time I've come across anything like that in the tree.

**Comment by rambaut** [comment]
My guess is they each just have a few of the mutations in common (or ambiguities - i.e. R, Y W?). There is way too much diversity in that cluster for it to be real.

**Comment by rambaut** [comment]
An ML tree of the above genomes doesn't have the long branch in it... (data not shown)

**Comment by AngieHinrichs** [comment]
Is it ignoring ambiguous bases?  Still looking into how many calls are real vs. ambiguous, but of the 21 mutations on our long branch, at least 5 are unambiguous in most of the sequences.  VCF format (AC= number with alternate allele, AN= number with non-N base call):
```
NC_045512v2     2698    T2698A  T     A .       .       AC=229;AN=251
NC_045512v2     6990    C6990A  C     A .       .       AC=243;AN=254
NC_045512v2     7469    G7469T  G     T .       .       AC=249;AN=254
NC_045512v2     14071   G14071T G     T .       .       AC=218;AN=254
NC_045512v2     15796   C15796A C     A .       .       AC=254;AN=254
```

**Comment by rambaut** [comment]
How does usher deal with ambigous bases?

**Comment by AngieHinrichs** [comment]
It doesn't penalize a mismatch between a real base and a compatible ambiguous base, it treats them as a match.  So a few sequences with real base call differences can attract a lot of sequences with ambiguous base calls at those positions.

An additional 7 of the 21 are ambiguous in >200 of the 254:
```
NC_045512v2     3239    G3239W  G     W .       .       AC=208;AN=254
NC_045512v2     10787   G10787W G     W .       .       AC=221;AN=231
NC_045512v2     19078   G19078K G     K .       .       AC=250;AN=254
NC_045512v2     22672   T22672W T     W .       .       AC=240;AN=253
NC_045512v2     23885   G23885W G     W .       .       AC=253;AN=254
NC_045512v2     29148   T29148W T     W .       .       AC=226;AN=254
NC_045512v2     29395   G29395K G     K .       .       AC=209;AN=253
```

Here's the unfiltered VCF for the 21:
```
NC_045512v2     1319    G1319K,G1319T G K,T     .       .       AC=167,83;AN=253
NC_045512v2     2698    T2698A,T2698W T A,W     .       .       AC=229,22;AN=251
NC_045512v2     3239    G3239W,G3239D G W,D     .       .       AC=208,46;AN=254
NC_045512v2     3947    G3947T,G3947K,G3947W,G3947D,G3947R      G       T,K,W,D,R       .       .       AC=197,7,15,2,1;AN=222
NC_045512v2     6589    G6589T,G6589K G T,K     .       .       AC=184,68;AN=254
NC_045512v2     6660    G6660K,G6660T,G6660B,G6660D     G       K,T,B,D .       .       AC=93,57,3,2;AN=156
NC_045512v2     6990    C6990A,C6990M,C6990T    C       A,M,T   .       .       AC=243,10,1;AN=254
NC_045512v2     7469    G7469T,G7469K G T,K     .       .       AC=249,5;AN=254
NC_045512v2     10787   G10787W,G10787H,G10787T,G10787A G       W,H,T,A .       .       AC=221,5,2,3;AN=231
NC_045512v2     11537   A11537T,A11537W A       T,W     .       .       AC=199,55;AN=254
NC_045512v2     13824   C13824M,C13824A C       M,A     .       .       AC=197,55;AN=252
NC_045512v2     14071   G14071K,G14071T G       K,T     .       .       AC=36,218;AN=254
NC_045512v2     15796   C15796A C     A .       .       AC=254;AN=254
NC_045512v2     19078   G19078K,G19078T G       K,T     .       .       AC=250,4;AN=254
NC_045512v2     22672   T22672W,T22672A T       W,A     .       .       AC=240,13;AN=253
NC_045512v2     23885   G23885W,G23885K G       W,K     .       .       AC=253,1;AN=254
NC_045512v2     23943   T23943A,T23943W T       A,W     .       .       AC=94,154;AN=249
NC_045512v2     29148   T29148W,T29148A T       W,A     .       .       AC=226,28;AN=254
NC_045512v2     29395   G29395K,G29395T G       K,T     .       .       AC=209,44;AN=253
NC_045512v2     29414   G29414R,G29414A,G29414D,G29414H,G29414K,G29414W,G29414V,G29414M,G29414T,G29414B,G29414S G       R,A,D,H,K,W,V,M,T,B,S   .       .       AC=84,50,40,4,4,27,7,9,5,1,1;AN=240
NC_045512v2     29434   G29434K,G29434T,G29434W,G29434D,G29434R,G29434B G       K,T,W,D,R,B     .       .       AC=39,118,59,20,1,1;AN=239
```

**Comment by AngieHinrichs** [comment]
At the 21 positions on that long branch, of the 254 sequences, only 16 have any unambiguous reference alleles, and none of them have more than one unambiguous reference allele.  So those 254 sequences are at least very consistent about having either an alternate A or T or compatible ambiguous base call at those 21 positions.

**Comment by AngieHinrichs** [comment]
Some more positions that have mostly ambiguous or alt T bases:
```
NC_045512v2     1679    G1679K,G1679T G K,T     .       .       AC=201,53;AN=254
NC_045512v2     8152    C8152H,C8152M,C8152W    C       H,M,W   .       .       AC=23,222,9;AN=254
NC_045512v2     23948   G23948D,G23948W,G23948K,G23948R,G23948T,G23948H,G23948A,G23948V G       D,W,K,R,T,H,A,V .       .       AC=62,90,67,13,3,2,2,1;AN=241
NC_045512v2     25337   G25337K,G25337T G       K,T     .       .       AC=152,102;AN=254
NC_045512v2     25455   G25455T,G25455K G       T,K     .       .       AC=28,226;AN=254
NC_045512v2     25471   G25471K,G25471T G       K,T     .       .       AC=209,43;AN=253
NC_045512v2     27327   G27327K,G27327T G       K,T     .       .       AC=122,131;AN=253
```

It's debatable whether usher should accept ambiguous base calls as truly compatible with real base calls, but again, despite having seen a lot of odd little branches in our tree, this is the first time I have seen a very long branch with a large cluster of sequences at the end.  And as Russ pointed out, they're all from a small range of dates and the unambiguous alts are all A or T.  So I wonder if there could have been a hiccup in the processing of these sequences... could it have anything to do with the transition from ARTIC v3 to v4, for example?  (Or not, I'm just wondering because of the timing.)

**Comment by AngieHinrichs** [comment]
cov2tree.org turned up a smaller branch with 7 more sequences from England, collected 25-30 June, with A, T or ambiguous at the same 21 positions as the first branch:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/anotherLongBranchInDelta.json?label=nuc%20mutations:C19983T
```
England/ALDP-182C7A4/2021       2021-06-25
England/ALDP-182C66B/2021       2021-06-29
England/MILK-182D3BE/2021       2021-06-29
England/MILK-182D512/2021       2021-06-29
England/MILK-182D178/2021       2021-06-30
England/MILK-182D309/2021       2021-06-30
England/MILK-182D59A/2021       2021-06-30
```
```
NC_045512v2     1319    G1319K,G1319T G K,T     .       .       AC=2,5;AN=7
NC_045512v2     2698    T2698A  T     A .       .       AC=7;AN=7
NC_045512v2     3239    G3239D,G3239W G D,W     .       .       AC=3,4;AN=7
NC_045512v2     3947    G3947T,G3947W G T,W     .       .       AC=6,1;AN=7
NC_045512v2     6589    G6589K,G6589T G K,T     .       .       AC=4,3;AN=7
NC_045512v2     6660    G6660T,G6660K G T,K     .       .       AC=3,2;AN=5
NC_045512v2     6990    C6990A,C6990M C A,M     .       .       AC=6,1;AN=7
NC_045512v2     7469    G7469T  G     T .       .       AC=7;AN=7
NC_045512v2     10787   G10787W G     W .       .       AC=7;AN=7
NC_045512v2     11537   A11537W,A11537T A       W,T     .       .       AC=3,4;AN=7
NC_045512v2     13824   C13824M,C13824A C       M,A     .       .       AC=4,3;AN=7
NC_045512v2     14071   G14071T,G14071K G       T,K     .       .       AC=5,2;AN=7
NC_045512v2     15796   C15796A C     A .       .       AC=7;AN=7
NC_045512v2     19078   G19078K G     K .       .       AC=7;AN=7
NC_045512v2     22672   T22672W T     W .       .       AC=7;AN=7
NC_045512v2     23885   G23885W G     W .       .       AC=7;AN=7
NC_045512v2     23943   T23943A,T23943W T       A,W     .       .       AC=2,5;AN=7
NC_045512v2     29148   T29148W T     W .       .       AC=7;AN=7
NC_045512v2     29395   G29395K,G29395T G       K,T     .       .       AC=6,1;AN=7
NC_045512v2     29414   G29414W,G29414D,G29414A,G29414R,G29414H G       W,D,A,R,H       .       .       AC=2,1,2,1,1;AN=7
NC_045512v2     29434   G29434T,G29434D,G29434W G       T,D,W   .       .       AC=4,1,2;AN=7
```
And one last little branch with 4 more samples:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/oneLastLongBranchInDelta.json?c=country&label=nuc%20mutations:T28726A
```
England/ALDP-182C926/2021       2021-06-29
England/MILK-182D07B/2021       2021-06-30
England/MILK-182D0C6/2021       2021-06-30
England/MILK-182D5A9/2021       2021-06-30
```
```
NC_045512v2     1319    G1319K  G     K .       .       AC=4;AN=4
NC_045512v2     2698    T2698A  T     A .       .       AC=4;AN=4
NC_045512v2     3239    G3239W  G     W .       .       AC=4;AN=4
NC_045512v2     3947    G3947T  G     T .       .       AC=4;AN=4
NC_045512v2     6589    G6589K,G6589T G K,T     .       .       AC=2,2;AN=4
NC_045512v2     6660    G6660T,G6660K G T,K     .       .       AC=2,2;AN=4
NC_045512v2     6990    C6990A  C     A .       .       AC=4;AN=4
NC_045512v2     7469    G7469T  G     T .       .       AC=4;AN=4
NC_045512v2     10787   G10787W G     W .       .       AC=4;AN=4
NC_045512v2     11537   A11537T,A11537W A       T,W     .       .       AC=3,1;AN=4
NC_045512v2     13824   C13824M C     M .       .       AC=4;AN=4
NC_045512v2     14071   G14071T G     T .       .       AC=4;AN=4
NC_045512v2     15796   C15796A C     A .       .       AC=4;AN=4
NC_045512v2     19078   G19078K G     K .       .       AC=4;AN=4
NC_045512v2     22672   T22672W T     W .       .       AC=4;AN=4
NC_045512v2     23885   G23885W G     W .       .       AC=4;AN=4
NC_045512v2     23943   T23943W T     W .       .       AC=4;AN=4
NC_045512v2     29148   T29148W T     W .       .       AC=4;AN=4
NC_045512v2     29395   G29395T,G29395K G       T,K     .       .       AC=1,3;AN=4
NC_045512v2     29414   G29414A,G29414D,G29414K,G29414R G       A,D,K,R .       .       AC=1,1,1,1;AN=4
NC_045512v2     29434   G29434W,G29434K,G29434T G       W,K,T   .       .       AC=1,1,1;AN=3
```

**Comment by AngieHinrichs** [comment]
I noticed that the sequence IDs were all in the range 182AD1D - 182D600, so I looked for other sequences in that range and found a few more that didn't end up in clusters, but just as lone sequences with a lot of extra mutations.

In B.1.1.7:
```
Scotland/QEUH-182B0D7/2021      2021-07-01
Scotland/QEUH-182B20E/2021      2021-07-01
```
In B.1.617.2:
```
England/ALDP-182C8DE/2021       2021-06-29
```
There were also 35 sequences with IDs in the range that are also in GenBank.  Spot-checking, these sequences seem to *not* suffer from the excess A/T/ambig problem:
```
England/BRBR-182D011/2021       OU411712.1      2021-06-30
England/BRBR-182CA7E/2021       OU411672.1      2021-06-28
England/QEUH-182C407/2021       OU411894.1      2021-07-01
England/BRBR-182CAF6/2021       OU411697.1      2021-06-30
Scotland/QEUH-182D64C/2021      OU407287.1      2021-07-01
England/BRBR-182CA6F/2021       OU411686.1      2021-06-30
Scotland/QEUH-182D6F1/2021      OU407301.1      2021-07-01
Scotland/QEUH-182C434/2021      OU411879.1      2021-07-01
Scotland/QEUH-182C452/2021      OU411886.1      2021-07-01
Scotland/QEUH-182D688/2021      OU407284.1      2021-07-01
England/QEUH-182C416/2021       OU411880.1      2021-07-01
Scotland/QEUH-182D6C4/2021      OU407286.1      2021-07-01
Scotland/QEUH-182D6A6/2021      OU407314.1      2021-07-01
Scotland/QEUH-182D63D/2021      OU407030.1      2021-07-01
England/BRBR-182CAD8/2021       OU411943.1      2021-06-30
Scotland/QEUH-182D66A/2021      OU407025.1      2021-07-01
England/QEUH-182D65B/2021       OU407315.1      2021-07-01
Scotland/QEUH-182D62E/2021      OU407306.1      2021-07-01
England/BRBR-182D002/2021       OU411737.1      2021-06-30
England/BRBR-182CAC9/2021       OU411660.1      2021-06-30
England/QEUH-182C443/2021       OU411872.1      2021-07-01
England/BRBR-182D020/2021       OU411996.1      2021-06-30
Scotland/QEUH-182D6E2/2021      OU407290.1      2021-07-01
Scotland/QEUH-182D697/2021      OU407051.1      2021-07-01
England/BRBR-182CAE7/2021       OU411696.1      2021-06-30
England/QEUH-182D6D3/2021       OU407298.1      2021-07-01
England/BRBR-182CABA/2021       OU411656.1      2021-06-30
Scotland/QEUH-182C470/2021      OU411866.1      2021-07-01
England/BRBR-182CA9C/2021       OU411940.1      2021-06-30
Scotland/QEUH-182D6B5/2021      OU407057.1      2021-07-01
Scotland/QEUH-182D679/2021      OU407299.1      2021-07-01
England/BRBR-182CA8D/2021       OU411701.1      2021-06-29
England/BRBR-182D03F/2021       OU411720.1      2021-06-30
Scotland/QEUH-182C461/2021      OU411897.1      2021-07-01
England/BRBR-182CAAB/2021       OU411662.1      2021-06-30
```
The following 49 sequences are in the range of IDs, but not in the UCSC tree.  34 of them were excluded because they had too many equally parsimonious placements (>5).  The other 15 may have been added but then filtered out due to internal branch with >30 mutations or having >20 private mutations, but it would take more digging to confirm that.
```
England/ALDP-182B866/2021
England/ALDP-182C4AD/2021
England/ALDP-182C57D/2021
England/ALDP-182C59B/2021
England/ALDP-182C5AA/2021
England/ALDP-182C5C8/2021
England/ALDP-182C610/2021
England/ALDP-182C67A/2021
England/ALDP-182C72C/2021
England/ALDP-182C786/2021
England/ALDP-182C856/2021
England/ALDP-182C917/2021
England/ALDP-182C944/2021
England/ALDP-182C99F/2021
England/ALDP-182C9AE/2021
England/ALDP-182C9BD/2021
England/ALDP-182C9CC/2021
England/ALDP-182C9DB/2021
England/MILK-182D0D5/2021
England/MILK-182D15A/2021
England/MILK-182D345/2021
England/MILK-182D442/2021
England/MILK-182D4CA/2021
England/MILK-182D55E/2021
England/MILK-182D5C7/2021
England/MILK-182D5E5/2021
England/PLYM-182B2E0/2021
England/PLYM-182B3CF/2021
England/PLYM-182B417/2021
England/PLYM-182B514/2021
England/PLYM-182B6A8/2021
England/PLYM-182B6D5/2021
England/PLYM-182CA23/2021
England/QEUH-182AF62/2021
Scotland/QEUH-182AD0E/2021
Scotland/QEUH-182AD4A/2021
Scotland/QEUH-182AE47/2021
Scotland/QEUH-182AEA1/2021
Scotland/QEUH-182AF71/2021
Scotland/QEUH-182AFBD/2021
Scotland/QEUH-182AFF9/2021
Scotland/QEUH-182B031/2021
Scotland/QEUH-182B040/2021
Scotland/QEUH-182B09B/2021
Scotland/QEUH-182B13E/2021
Scotland/QEUH-182B23B/2021
Scotland/QEUH-182B259/2021
Scotland/QEUH-182B277/2021
Scotland/QEUH-182B2D1/2021
```

**Comment by rambaut** [comment]
OK - yes, there is something very wrong with these sequences... In this image, most of the black tick marks are IPAC ambiguity codes (mostly `K` or `W`). 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/686405/126749568-545519fe-f416-4efa-9e49-45b62529da9d.png">

A close up example: 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/686405/126749877-24895329-bc11-45de-aefa-ff7e58978afe.png">

**Comment by rambaut** [comment]
OK. Looks like a bad sequencing run according to @nickloman and Jeff Barrett - they mumbled something about dodgy reagents. These genomes will be removed. Thanks for picking this up and noticing the unusual patterns. I don't think this is something we can expect `usher` or other tree building software to deal with and in future it will be flagged earlier in QC.

Closing the issue.

**Comment by rambaut** [comment]
Unclosed the issue until it is finally resolved.

**Comment by AngieHinrichs** [comment]
OK, makes sense to remove the sequences, thanks!

**Comment by nickloman** [comment]
We've tracked this issue down to sequencing error at one of the sequencing sites and we will advise that these sequences should be suppressed from the COG dataset. I've asked a representative at the sequencing site to provide further information on this ticket in case useful for others in the future. We will also be looking at putting in a new filter for sequences with a certain % of mixed bases to fail automated quality control at the CLIMB side.

**Comment by SamStudio8** [comment]
I believe these sequences were suppressed by the uploader, so will close this now.

**Comment by theosanderson** [comment]
I chased this up as I think we (Sanger, not COG) ended up suppressing this on COG but not yet withdrawing from the databases. The withdrawals should now be happening, at least for the original sequences that @AngieHinrichs flagged, and I'll see if I can figure out what the full affected set is.
