### ISSUE TITLE
[validator] SUPERSCRIPT III - TAQMAN 7500	

### ISSUE THREAD

**Issue by happykhan** [COG-UK/dipi-group#143]
**Brief description**

These are diag assays for samples from DHSC 

**Detail**

| Validator | Field       | Proposed option | Justification                    |
|-----------|-------------|-----------------|----------------------------------|
| ~ct~        |~test_platform~|~TAQMAN 7500~|use `APPLIED_BIO_7500`|
| ct        |test_kit|~SUPERSCRIPT III~ `INVITROGEN`||

***
**Proposed by:** Alikhan -NORW 

* [x ] I have read the documentation for the existing validators and there is no suitable entry
* [x ] This is not a request to add a sequencing platform which has its own special form

***
***

**FOR DEVELOPER USE**

* [x] Add field validation to Majora forms
* [x] Add field to API docs
* [x] Push to Majora prod
* [x] Update validator spreadsheet (if applicable)
* [x] Update CLIMB-COVID data changelog

**Comment by SamStudio8** [comment]
It appears as though the Taqman 7500 might already be covered with `APPLIED_BIO_7500` (https://www.gene-quantification.de/abi7500.pdf), I think the Taqman brand is a red herring

**Comment by SamStudio8** [comment]
Naming convention for the `test_kit` would use the manufacturer name, please confirm that `INVITROGEN` is suitable for SuperScript™ III Platinum™ One-Step qRT-PCR Kit (the kit we think you are referring to).

**Comment by happykhan** [comment]
Hi sam. 
OK
 that sound good. so just adding test_kit: INVITROGEN  
is good for me !

**Comment by tombch** [comment]
Hello @happykhan, the change has been made!

**Comment by SamStudio8** [comment]
Welcome to CLIMB-COVID and congratulations on your first Majora contribution @tombch :tada: :rocket:
