### ISSUE TITLE
cog_all.fasta etc. files not updated in 6 days?

### ISSUE THREAD

**Issue by AngieHinrichs** [COG-UK/dipi-group#144]
Hello!  Hopefully this will have worked itself out by the time you see this, but just in case (and please let me know if I should report this elsewhere) -- the wonderful cog_all.fasta, cog_metadata.csv etc. download files are usually updated every day or two, but they seem not to have been updated since last Sunday:
```
curl -s -I https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta | grep Last-Modified
Last-Modified: Sun, 17 Oct 2021 19:08:47 GMT

curl -s -I https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_metadata.csv | grep Last-Modified
Last-Modified: Sun, 17 Oct 2021 19:13:46 GMT
```
Can you unstick whatever got stuck there?  Thanks!

**Comment by rmcolq** [comment]
I've manually triggered the s3 upload for a run starting on the 22nd. 
File corruptions have made datapipe a somewhat manual process over the last few days, and it therefore hadn't triggered the s3 upload on completion.

**Comment by SamStudio8** [comment]
Closing as I can see 2021-10-24 has been uploaded

**Comment by AngieHinrichs** [comment]
Thanks so much @rmcolq, sorry to hear about the systems troubles & glad to have the latest again!
