### ISSUE TITLE
Metadata file seems incomplete

### ISSUE THREAD

**Issue by Jeltje** [COG-UK/dipi-group#147]
Hello all,

In today's download of https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta I count 1,191,934 sequences, but 
cog_metadata.csv (also downloaded today) only contains 1,060,868 entries.
This means there are 131,066 samples missing from the metadata file.

I checked and all metadata IDs correspond to fasta IDs; there's no mismatch.
A sampling of IDs with missing metadata:
```
Scotland/CVR11593/2021
England/MILK-1F9CB7F/2021
England/PLYM-18CA22F/2021
Wales/PHWC-26B03/2020
England/BRBR-1B3F37A/2021
England/BRBR-1D8E37A/2021
England/MILK-1B87E09/2021
England/NEWC-1B4CCBB/2021
Wales/PHWC-PRKC8W/2021
England/QEUH-13549A2/2021
```

I'm assuming there's nothing wrong with the sequences?

**Comment by rmcolq** [comment]
There should be nothing wrong with the sequences. I've been dealing with file corruption issues and for the short term have been focussing on getting output, even if it sacrifices some sequences.

**Comment by rmcolq** [comment]
I can confirm that in the latest data release there are the same number of entries in the `https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_metadata.csv` as `https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_alignment.fasta`
