### ISSUE TITLE
[manualpipe] Asklepian 20211109

### ISSUE THREAD

**Issue by tombch** [COG-UK/dipi-group#153]
**Brief description**

[Provide a sentence of background]

**Pipeline exit code:** 70

***
**Executed by:** @tombch BIRM

* [x] I am sure this pipeline is not already running (**Only relevant for non-flocked pipelines**)

***
* [x] Engage pipeline via mqtt **from a clean dedicated mqtt environment**
* [ ] ~~Disable NXF cache destruction (only applicable for ENA BAM pipe)~~
* [ ] ~~Check output if necessary~~
* [x] Check mqtt message is sent confirming completion, or send one if required (check in #tael-steam)
* [ ] ~~Re-enable NXF cache destruction (if disabled)~~

***
* [x] Set appropriate issue flags and assignee

* [x] Manual intervention complete
* "Normal" service disrupted? **~~YES~~/NO**
* If yes, describe impact:

**Comment by SamStudio8** [comment]
Nice one gang @BioWilko @tombch 
The exit `70` is Ocarina having a panic as something has gone wrong with Majora that cannot be anticipated. Checking the logs it looks like the Majora uWSGI process was reaped by the OOM killer.

```
[pid: 27287|app: 0|req: 28749/549242] () () {54 vars in 779 bytes} [Tue Nov  9 16:57:47 2021] POST //api/v2/majora/task/get// => generated 290 bytes in 26 msecs (HTTP/1.1 200) 5 headers in 157 bytes (1 switches on core 0)
[2021-11-09 17:00:32] - DAMN ! worker 6 (pid: 27165) died, killed by signal 9 :( trying respawn ...
[2021-11-09 17:00:32] - Respawned uWSGI worker 6 (new pid: 1986)
```
