### ISSUE TITLE
Update #Inbound-distribution slack messages

### ISSUE THREAD

**Issue by BioWilko** [COG-UK/dipi-group#168]
The example commands provided within the `#Inbound-distribution` daily messages are broken currently.

The commands refer to `/cephfs/covid/bham/artifacts/published//elan/.missing.ls` when they should refer to `/cephfs/covid/bham/artifacts/published/elan/YYYYMMDD.missing.ls` with the current date.

**Comment by SamStudio8** [comment]
fixed by https://github.com/SamStudio8/elan-nextflow/commit/f2debcd0646b6b0886e6ad26580090f123b3f26d
