### ISSUE TITLE
Metadata file seems incomplete

### ISSUE THREAD

**Issue by Jeltje** [COG-UK/dipi-group#172]
In a download we did yesterday, I found 160,916 sample IDs in the fasta file that are not in the metadata file.
I have seen discrepancies like this for the past week so it doesn't look like a one time glitch.  

This [happened in October](https://github.com/COG-UK/dipi-group/issues/147) as well, don't know if it's a similar issue.

**Comment by rmcolq** [comment]
The metadata file is matched to the aligned fasta. Are you comparing with the file of all sequences?

**Comment by rmcolq** [comment]
I count 1439105 sequences in the aligned fasta and 1439105 non-header rows in the metadata. There are 1601285 sequences in the  full fasta - the difference are the sequences which fail our QC (but are made publicly available for completeness/openness). I think this explains your missing numbers.

**Comment by SamStudio8** [comment]
Judging by the :+1: here I think this has been solved!
