### ISSUE TITLE
Download files not updated in the past few days

### ISSUE THREAD

**Issue by AngieHinrichs** [COG-UK/dipi-group#205]
Hello DIPI group,

I download cog_metadata.csv.gz and cog_all.fasta.gz from https://cog-uk.s3.climb.ac.uk/phylogenetics/latest daily, and they are usually updated daily, but at the moment they seem to have not been updated since 5 days ago:
```
curl -s -I https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta.gz | grep Last-Modified
Last-Modified: Fri, 18 Mar 2022 02:07:29 GMT
```

Is this the right place to inquire about getting the daily updates of those files going again?  

Thanks,
Angie

**Comment by nickloman** [comment]
@WhalleyT

**Comment by t-whalley** [comment]
Hi @AngieHinrichs,

Apologies I've had an issue in uploading them to the S3 bucket, which seems to have been rectifified. Thanks for letting me know, it looks like the upload is working again now, but please let me know if that's not the case. 

Thanks, TOm

**Comment by AngieHinrichs** [comment]
Yes, got the updated files, thanks Tom!
