### ISSUE TITLE
Profile grapevine step 5 annotation

### ISSUE THREAD

**Issue by SamStudio8** [COG-UK/dipi-group#21]
Comparison of the time deltas on the recent SLURM logs show the step 5 clusterfunk annotation step takes two orders of magnitude longer than the comparable step 4 annotation. I am intrigued by this and want to run it through `cProfile` and see if there's any low hanging fruit to patch.

**Comment by rambaut** [comment]
I think all of the slowness in these grapevine steps are due to how Dendropy handles tree annotations and is largely due to the reading of the tree with annotations (presumably some very inefficient look-ups or string processing).

**Comment by SamStudio8** [comment]
@rambaut This stuck out as odd to me because we'd previously improved the annotation for step 4, and the invocation for step 5 is very similar. Interesting point about reading the annotations being the slow part. This seems a good theory - from my understanding the step 5 tree is larger and more heavily annotated than the step 4 tree. I guess there's just some worse than O(n) performance in that initial reading? I figured I'd profile it anyway as we have the scripts at hand, but mostly to satisfy my own morbid curiosity.

**Comment by asouthgate** [comment]
I have also noticed dendropy to have very poor performance for doing many things with trees. In fact, I never found a performant python library for this.

**Comment by rambaut** [comment]
Seems to be worse than O(n)

**Comment by SamStudio8** [comment]
This has been a really fun one.

### CProfile
The initial profile result was surprising. Immediately, one line stands out:

```
57899152486 11597.987    0.000 11599.850    0.000 taxonmodel.py:1690(_get_lower_cased_label)
```

### Case sensitivity

The `_get_lower_cased_label` function is called 57 billion times, taking 3.2 hours (under profile).
[`_get_lower_cased_label`](https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/datamodel/taxonmodel.py#L1690) is called by [`_lookup_label`](https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/datamodel/taxonmodel.py#L670).

So my understanding is that the taxa in the tree are managed by a `TaxonNamespace` object, which is case INsensitive by default. This means you can add `Bubo bubo` and `BUBO BUBO` to your tree and they'll magically be treated as the same taxon. This is achieved internally by using a [`lower_cased_label` property on the `Taxon` class](https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/datamodel/taxonmodel.py#L1696). 

Every fetch of the `lower_cased_label` results in a function call to `_get_lower_cased_label`. For some reason, [the lower case label is not added to a `Taxon` object when the label is set](https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/datamodel/taxonmodel.py#L1687). Every single fetch of this property has the overhead of a function call and requires checking two `if` statements. This also actually sets the lower cased label if it hasn't been requested before.

Whether the taxon namespace is case sensitive or not determines how `_lookup_label` works ([which is basically wrapped by `get_taxon`](https://github.com/jeetsukumaran/DendroPy/blob/main/src/dendropy/datamodel/taxonmodel.py#L1130) and the other taxon fetching functions). If the namespace is case insensitive (default), then [`_lookup_label` will fetch the `lower_cased_label` property](https://github.com/jeetsukumaran/DendroPy/blob/9a4eaca57ad5f05ffca9a4f25fed2de7511f4792/src/dendropy/datamodel/taxonmodel.py#L720) for comparison against the target label. If however, the namespace is case sensitive, [`_lookup_label` will fetch the `label` instead](https://github.com/jeetsukumaran/DendroPy/blob/9a4eaca57ad5f05ffca9a4f25fed2de7511f4792/src/dendropy/datamodel/taxonmodel.py#L715).

Unfortunately, the `label` is also a property, requiring a function call to (you guessed it): [`_get_label`](https://github.com/jeetsukumaran/DendroPy/blob/9a4eaca57ad5f05ffca9a4f25fed2de7511f4792/src/dendropy/datamodel/taxonmodel.py#L1683). However, this function immediately returns a string, rather than performing any `if` statements or the like.

I figured no if statements is better than two if statements and its reasonable to assume case sensitivity, especially in COG where the metadata annotations and sequence names are from the same source. I forked `clusterfunk` and changed the tree initialisation in `Main.py` to use a case sensitive namespace:

```
self.tree = dendropy.Tree.get(path=self.input, schema=self.input_format.lower(), preserve_underscores=True, taxon_namespace=dendropy.TaxonNamespace(is_case_sensitive=True), case_sensitive_taxon_labels=True)
```
Profiling this:

```
57899152486 5367.063    0.000 5367.063    0.000 taxonmodel.py:1683(_get_label)
```
Now we call `_get_label` instead of `_get_lower_cased_label` and spend 1.5 hours (under profile) doing so - theoretically doubling the speed of the step 5 annotation in `grapevine`.
Turns out, even basic function calls are not cheap, especially if you're doing 57 billion of them. I'm sure we can do better than this.

### Tree loading

I started wondering why there would be so many calls to this function in the first place (57 billion seems quite a large number). I had assumed this was because the annotation step in `clusterfunk` needs to find the taxon by its label, and that `dendropy` awkwardly achieves this with a linear scan through its taxon namespace, looking for the right `Taxon` object to add the annotation to.

It turns out, this is not the case! If we instead sort the initial profile results by cumulative time (which includes child functions):

```57899152486 11597.987    0.000 11599.850    0.000 taxonmodel.py:1690(_get_lower_cased_label)
   340292 9211.576    0.027 20812.541    0.061 taxonmodel.py:670(_lookup_label)
   340292    1.718    0.000 20814.259    0.061 taxonmodel.py:1101(get_taxon)
        1    0.000    0.000 20874.348 20874.348 nexusreader.py:598(_parse_taxa_block)
        1    6.618    6.618 20874.348 20874.348 nexusreader.py:635(_parse_taxlabels_statement)
        1    0.000    0.000 21025.580 21025.580 ioservice.py:258(read_tree_lists)
        1    0.000    0.000 21025.580 21025.580 nexusreader.py:343(_read)
        1    0.073    0.073 21025.580 21025.580 nexusreader.py:544(_parse_nexus_stream)
        1    0.000    0.000 21025.581 21025.581 treemodel.py:2561(_parse_and_create_from_stream)
        1    0.000    0.000 21025.591 21025.591 basemodel.py:133(_get_from)
        1    0.000    0.000 21025.591 21025.591 basemodel.py:193(get_from_path)
        1    0.000    0.000 21025.591 21025.591 treemodel.py:2674(get)
        1    0.000    0.000 21025.592 21025.592 Main.py:70(prepare_tree)
```
We discover that we spend over 5.8 hours (under profile) in `prepare_tree`, which is almost entirely because of `_lookup_label` and `_get_lower_cased_label`, which are ultimately called by `_parse_taxlabels_statement`. Contrary to my assumption, this isn't related to adding annotations.

More interestingly, [`_parse_taxlabels_statement`](https://github.com/jeetsukumaran/DendroPy/blob/9a4eaca57ad5f05ffca9a4f25fed2de7511f4792/src/dendropy/dataio/nexusreader.py#L635) is responsible for reading the `TAXLABELS` block of a `NEXUS` tree, not the `TREE` part. So this performance penalty is not related to reading existing annotations from the tree either (which is a complete surprise to me, as the annotations model in `dendropy` is hilariously complex to an outsider like me).

It was then I realised the true horror of what was happening, and why there were so many function calls.

When reading through the `TAXLABELS` block, [the parsing function first checks to see whether the label is already in the tree](https://github.com/jeetsukumaran/DendroPy/blob/9a4eaca57ad5f05ffca9a4f25fed2de7511f4792/src/dendropy/dataio/nexusreader.py#L651). For a fresh namespace, this triggers a worst case linear scan through the tree, for every, single, taxon.
On my test tree selected from a run of `grapevine` in the previous week, there were 340,000 taxon labels. For the `i`'th label, one must scan `i-1` labels, therefore the cumulative sum of taxon labels to check can be accurately predicted as the triangular number of the `n` labels to be inserted into the tree:

```
n*(n+1) / 2 = (340000*340001)/2 = 57,800,170,000
```

The billions of label fetches are because we're scanning the taxon namespace `n` times at worst case; yielding O(n^2) performance for every insertion.

### Patch

Clearly in comparison to this finding, the case sensitivity patch to `clusterfunk` is small-fry. I've forked `dendropy` and taken a look at `_parse_taxlabels_statement` instead. We want to avoid linear hits to the taxon namespace. I figured the most straightforward thing to do is emulate the linear scan conducted by `_lookup_label`, but just do it once; keeping a local copy of the labels as a set. Instead of a linear scan of the namespace for each insertion, we can now check whether to fetch or insert a new taxon by screening the label against a set in constant time.

The hard part is considering the case sensitivity, we need to make sure that we don't accidentally add a new taxon to the namespace if it already exists in other casing (for case insensitive). This turned out to be reasonably easy, as we can again emulate the behaviour of `_lookup_label`. For case insensitive (ie. using the lower case labels), we add all the `taxon.lower_cased_label` already in the namespace to our set, otherwise we add `taxon.label`. The gotcha is we must also remember to lowercase the new token from the `TAXLABEL` block if we're in case insensitive mode (because the token could have any casing, but we need to treat it as lowercase, just like `new_taxon` would).

I've implemented this (https://github.com/SamStudio8/DendroPy/commit/fa9fe29403bfd263a2fc93e95dd41df29aa1fdbc), and added two new tests to the impressively extensive dendropy test suite that ensure that the label set behaves appropriately for reading `NEXUS` trees, regardless of their case, under the two options.

In terms of performance:

```
        1    0.000    0.000  168.393  168.393 Main.py:70(prepare_tree)
```

```
        1    1.086    1.086   21.463   21.463 nexusreader.py:635(_parse_taxlabels_statement)
```

Parsing the `taxlabels` now takes 21 seconds (under profile), and preparing the tree in `clusterfunk` takes around 3 minutes.
Outside the performance constraints of deep profiling, the step 5 annotation now runs start to finish in less than five minutes, whereas previously it took nearly two hours. This patch will prove useful going forward as triangular numbers grow so quickly, the performance will continue to degrade quite significantly with each additional new taxon in the tree.

### Pull request

I've formally suggested this patch to `dendropy`. See https://github.com/jeetsukumaran/DendroPy/pull/129.
I'm hoping this work is accepted, but in the case that it is not, we may want to operate a fork of `dendropy` on the COG-UK organisation for `grapevine` to use instead.

**Comment by rmcolq** [comment]
Wow! This looks like an awesome speed up - thanks Sam!

**Comment by SamStudio8** [comment]
This patch has been accepted upstream at `dendropy` and integrated into `v4.5.2`, and is now packaged in `pyPI`.
@rmcolq Would you be willing to [bump the version pin](https://github.com/COG-UK/grapevine/blob/master/environment.yml#L46) to `>=4.5.2` and update the production `grapevine` environment?

**Comment by rmcolq** [comment]
Done!

**Comment by SamStudio8** [comment]
Thrilled to see this paying off - looks like we've cut around 100 minutes off the annotation step in production!

Before average:
```
step_5_annotate_tree  6   1:49:25.166667
```

After average:
```
step_5_annotate_tree    2       0:02:08
```

Closing :100:

**Comment by rambaut** [comment]
Superb. Nice work Sam.
