### ISSUE TITLE
https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/ URLs get error 443 (Connection timed out)

### ISSUE THREAD

**Issue by AngieHinrichs** [COG-UK/dipi-group#213]
Hi all!  For years I've been fetching these URLs every day:

https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta.gz
https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_metadata.csv.gz

But for the past few days my scripts have been failing when my curl command
```
curl -S -s -C - -O https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta.gz
```
gets this error:
```
curl: (7) Failed connect to cog-uk.s3.climb.ac.uk:443; Connection timed out
```
Hopefully it's just a matter of something needing a restart?

Thanks,
Angie

**Comment by rmcolq** [comment]
There was an electrical fault in the Birmingham datacenter on Friday (5/7/24) which meant a total shutdown of all CLIMB hardware, including CLIMB-COVID. Should hopefully be back online soon

**Comment by AngieHinrichs** [comment]
Thank you @rmcolq!

**Comment by BioWilko** [comment]
We're slowly bringing things back up today, I'll ping here when S3 is back :)

**Comment by BioWilko** [comment]
Okay that should be back now, let us know if you have any more problems!

**Comment by AngieHinrichs** [comment]
Working great now, thank you @BioWilko!
