### ISSUE TITLE
S3 files not updated since 2024-09-18

### ISSUE THREAD

**Issue by AngieHinrichs** [COG-UK/dipi-group#214]
Hello again!  It looks like the S3 download fasta and metadata files have not been updated in a bit over a week -- does something need a restart?
```
curl -s -I https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta.gz | grep Last-Modified
Last-Modified: Wed, 18 Sep 2024 23:21:38 GMT
```

Thanks!

**Comment by BioWilko** [comment]
Hi Angie

I believe datapipe was not running in that time, sounds like the listener just needed a restart. @WhalleyT can update further.

**Comment by t-whalley** [comment]
Hi @AngieHinrichs, I'm not 100% sure on the exact cause of it was. My listener script was running but I couldn't access the directory where the pipeline was being ran and the process was caught meaning that I wasn't notified of any failure because it was stuck in essence. Whatever problem seems to be sorted now and I can access the directories etc. so I've manually restarted the latest accessions (yesterday, 29th September) so they should catch up

**Comment by AngieHinrichs** [comment]
Great, thank you @BioWilko and @WhalleyT!

**Comment by AngieHinrichs** [comment]
Looks like the files last updated 24th December, @WhalleyT when you have time can you take a look?

**Comment by BioWilko** [comment]
It seems to be related to the Gisaid API being down, nobody I've spoken to seems to be able to access it currently...

**Comment by AngieHinrichs** [comment]
That's concerning... thanks for looking into it!

**Comment by AngieHinrichs** [comment]
Happy New Year!  Once again the COG S3 files seem not to have been updated since before the holidays:
```
curl -s -I https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_all.fasta.gz | grep Last-Modified
Last-Modified: Mon, 22 Dec 2025 03:06:21 GMT
```
Can someone take a look?  Thanks.

**Comment by BioWilko** [comment]
Can you have a look at this @t-whalley?

**Comment by t-whalley** [comment]
Hi all, looks like there was a down period over Christmas where Datapipe didn't need to run for long enough that the latest output directory (that new runs of the pipeline use to fetch old results) got caught up in some file cleanup. I've manually restarted stuff so it should be back up some time tomorrow
