### ISSUE TITLE
Produce naive variants csv as sqlite database

### ISSUE THREAD

**Issue by m-bull** [COG-UK/dipi-group#23]
It would be great to have naive variants csv as an sqlite database to make it quicker to query. My current approach to variant type the csv takes ~2h, but anticipate this would be greatly reduced with a database. Hopefully not too expensive to add onto the [asklepian](https://github.com/SamStudio8/asklepian/) workflow.

**Comment by SamStudio8** [comment]
I've actually got a script knocking around to generate the variants table as an sqlite for emergencies! I should be able to add this to the end of Asklepian. It takes around 20 minutes I think. The index makes it quite large so I suggest the script does something like:

* generates a new sqlite db, index it
* perform a count query and check the number of rows matches expectation
* update a `latest.sqlite` symlink to the new db
* delete the previous db

**Comment by SamStudio8** [comment]
Additionally I could hook this into [vex](https://github.com/SamStudio8/vex) and get a little API going!

**Comment by m-bull** [comment]
> 
> 
> I've actually got a script knocking around to generate the variants table as an sqlite for emergencies! I should be able to add this to the end of Asklepian. It takes around 20 minutes I think. The index makes it quite large so I suggest the script does something like:
> 
>     * generates a new sqlite db, index it
> 
>     * perform a count query and check the number of rows matches expectation
> 
>     * update a `latest.sqlite` symlink to the new db
> 
>     * delete the previous db

I think this is a good approach. Thinking aloud, it would be nice to have `metdata.matched` as another table in the same db...

Obviously caution required if that's included and its vexed.

**Comment by SamStudio8** [comment]
> Thinking aloud, it would be nice to have metdata.matched as another table in the same db...

Now you're just asking for a second Majora... I think you're right though, it would perhaps be nice to pre-package some of the most used metadata into an sqlite3 db for people to query. I think there's a lot to be resolved first - ideally I'd want people to query the metadata from Majora (and have common queries cached) rather than the master table. `ocarina` could even have a `--db` option or something to help generate local databases.

**Comment by SamStudio8** [comment]
Added by https://github.com/SamStudio8/asklepian/commit/53fb57793699ae37753615de9865471a22d817ad. I've added a `tael` hook to run the `go_db.sh` script after `asklepian` runs. We'll see how this runs tonight.

**Comment by SamStudio8** [comment]
@m-bull has been using this already, and I see the updates over the weekend worked automatically as planned. I have some changes I want to make (adding more columns, and both `aa`/`nt` co-ordinates) but that's for another issue.

**Comment by m-bull** [comment]
Tests over the weekend show that I can run my csv parsing code in ~25s using sqlite, rather than ~2h using the flatfile.

Success, please close if you're happy @SamStudio8.
