### ISSUE TITLE
Add new test_platform and test_kit values for Thermo Fisher Amplitude 

### ISSUE THREAD

**Issue by MattBashton** [COG-UK/dipi-group#36]
**Brief description**

A large testing site is now operational which will be using this platform, I need new API validators in `test_platform` and `testk_kit` to capture it.

**Detail**

Testing platform is described as "Thermo Fisher Scientific Amplitude Solution", an adequate `manufacturer_platform` encoding would thus be `THERMO_AMPLITUDE`.  See marketing [material](https://www.thermofisher.com/uk/en/home/clinical/clinical-genomics/pathogen-detection-solutions/amplitude-solution.html).

The kit used is described as "TaqPath COVID-19 HT Kit" of which the Covid and Kit parts are a given, so possibly a good name would be `TAQPATH_HT`.  See marketing [material](https://www.thermofisher.com/uk/en/home/clinical/clinical-genomics/pathogen-detection-solutions/amplitude-solution/high-throughput-kit.html).

| Validator | Field       | Proposed option | Justification                    |
|-----------|-------------|-----------------|----------------------------------|
| ct        |test_platform|THERMO_AMPLITUDE|Not covered by `test_platform`|
| ct        |test_kit|TAQPATH_HT|Not covered by `test_kit`|

***
**Proposed by:** Matt Bashton (NORT)

* I have read the documentation for the existing validators and there is no suitable entry

***
* [x] Add field validation to Majora forms https://github.com/SamStudio8/majora/commit/9593a783676c9474834cc8f4c8edec9fe86ac4b7
* [x] Add field to API docs https://github.com/SamStudio8/majora-docs/commit/17b75817f835309b491ccf3fee690ae28762ed13
* [x] Push to Majora prod
* [x] Update validator spreadsheet (if applicable)

**Comment by SamStudio8** [comment]
Done!
