### ISSUE TITLE
[elan] What to do with invalid consensus characters (e.g. `-`)

### ISSUE THREAD

**Issue by SamStudio8** [COG-UK/dipi-group#38]
We've noticed a site submitting MSA sequences as FASTA, containing deletion characters `-`. It appears some downstream software silently converts these to `N`. Seems to me that Elan should strip these out. Options:

* Elan should QC fail and abort sequences with invalid characters
* Elan should quietly strip `-` from sequences

**Comment by SamStudio8** [comment]
RC is now handling these in `datapipe` while we make a decision on what to do with Elan.

**Comment by SamStudio8** [comment]
* Phylopipe and Datapipe will handle this correctly with RC patch
* Asklepian should be patched to handle this
* Existing "published" sequences will remain untouched for now (this hits a wider problem, we don't handle updates, even gracefully)
* Decision on what to do going forward has been referred to DWG (calling conventions, Elan behaviour to be decided)

**Comment by SamStudio8** [comment]
Fix for `Asklepian` will involve stripping bad chars here: https://github.com/SamStudio8/asklepian/blob/main/get_best_ref.py#L101. Will raise this change tomorrow before we commit.

**Comment by SamStudio8** [comment]
* Changed by https://github.com/SamStudio8/asklepian/commit/22e58af5d4442d291402c84e204f7c7c234de382 in Asklepian
* RC confirms the change has been implemented in datapipe, gisaid-datapipe, phylopipe2 but not phylopipe1 (which is only getting stability updates going forward)
* This is now an open question at the DWG

**Comment by rambaut** [comment]
If sites are uploading aligned sequences with deletions encoded as `-`, that might mean that insertions relative to reference would be removed? This could be problematic going forward. Perhaps rejecting these sequences would be a more robust solution?

**Comment by SamStudio8** [comment]
@rambaut Agreed. I think my preference would be for Elan to outright reject these sequences as an Elan QC fail (which allows users to resubmit the data until it has been accepted). I think we could try and fast-track this decision through the data group this week if you're supportive of this change.

**Comment by nickloman** [comment]
I don't think that's how insertions would be encoded - we could check with the relevant site.

**Comment by rambaut** [comment]
Most align to reference pipelines will remove insertions to maintain the sequence length. We should just say we don't want aligned sequences - it may be indicative of other issues. But the two solutions are independent - we can strip bad characters if they are not rejected.

**Comment by nickloman** [comment]
Yes - although in this particular situation I don't think it applies. For previous sequences I think the ship has sailed and stripping the characters is the only way forward, but agree with principle of rejecting sequences with non-standard characters (anything not IUPAC) prospectively.

**Comment by SamStudio8** [comment]
This is a matter for the DWG
