### ISSUE TITLE
How to enable access to failed sequences

### ISSUE THREAD

**Issue by SamStudio8** [COG-UK/dipi-group#45]
Currently basic QC failed sequences are suppressed and unlinked from the artifact store. Some users would like to investigate properties of the failed genomes and will need access. I'll need to have a think how to enable this for existing sequences and new sequences going forward.

**Comment by anirpandit** [comment]
Some of the task we would be looking to do with the data is:

1. Number/proportion of sequences that fail over time
2. Range of coverage thresholds in the QC failed data across:
a. whole genome
b. Spike
c. RBD
3. Attempt VOC calls
a. bin into different coverage ranges
b. can we do anything to split across the vocs (suspect not unless we reduce the data to ones we suspect could be a specific VOC - e.g. travel list)
4. Estimate how likely we are to be able to call each of the variants consider

**Comment by SamStudio8** [comment]
NL makes the good point that most of the failed data is retained locally and has pointed in the direction of JB to provide some QC<50% data from WSI in the first instance. I think this would provide a good consistent data set to take a look at, NL has also done some local analysis of ONT data too. I'm going to close this for now but we can re-open it when our QC<50% data would prove useful.
