### ISSUE TITLE
[validator] Add Ion Torrent to instrument_make

### ISSUE THREAD

**Issue by richardemyers** [COG-UK/dipi-group#46]
Add Ion torrent to instrument make field

One of the commercial providers of sequence from returning overseas testing is using the ion torrent platform. this needs to be included in the instrument_make options 

**Detail**

| Validator | Field       | Proposed option | Justification                    |
|-----------|-------------|-----------------|----------------------------------|
| instrument_make | instrument_make |ION_TORRENT|Not in current list`|

***
**Proposed by:** [Myers/RE] [PHEC]

* [x] I have read the documentation for the existing validators and there is no suitable entry

***
* [x] Add field validation to Majora forms https://github.com/SamStudio8/majora/commit/b039aa5c3eac84acf6f12e51dde191d714a99720
* [x] Add field to API docs
* [x] Push to Majora prod
* [x] ~Update validator spreadsheet (if applicable)~ NA

**Comment by SamStudio8** [comment]
Confirmed `ION_TORRENT` is compatible with ENA's platform field. Will need to add permitted values to `pyENA` as appropriate when it comes to submissions to ENA (https://github.com/SamStudio8/pyena/blob/master/pyena/client.py#L24).

Valid options for instrument_model (if it were controlled) would be:

* Ion Torrent PGM
* Ion Torrent Proton
* Ion Torrent S5
* Ion Torrent S5 XL

See https://github.com/enasequence/schema/blob/master/src/main/resources/uk/ac/ebi/ena/sra/schema/SRA.common.xsd#L995-L999
