### ISSUE TITLE
[validator] Add `collection_pillar` for commercial suppliers

### ISSUE THREAD

**Issue by richardemyers** [COG-UK/dipi-group#48]
add a new pillar value for commercial sequencing

Need to be able to identify commercial seqs rapidly - international travellers

**Detail**

| Validator | Field       | Proposed option | Justification                    |
|-----------|-------------|-----------------|----------------------------------|
| collection_pillar   |collection_pillar | 3 | rapid identification of seqs from commercial suppliers |

***
**Proposed by:** [Myers RE | PHEC]

* [Y ] I have read the documentation for the existing validators and there is no suitable entry

***
* [x] Add field validation to Majora forms https://github.com/SamStudio8/majora/commit/a3dd6c858bab9e803ee6980d9f47381255da52d1
* [x] Add field to API docs
* [x] Push to Majora prod
* [x] ~Update validator spreadsheet (if applicable)~ NA

**Comment by SamStudio8** [comment]
Will assign option as `103` rather than `3` to avoid confusion with [existing pillars in government strategy](https://www.gov.uk/government/publications/coronavirus-covid-19-testing-data-methodology/covid-19-testing-data-methodology-note).
