### ISSUE TITLE
make biosample validity endpoint queries work with oauth

### ISSUE THREAD

**Issue by fschwach** [COG-UK/dipi-group#51]
currently, queries to the biosample validity endpoint  (api/v2/artifact/biosample/query/validity/) require old-style authentication which needs to be regularly refreshed manually. This is not ideal for automated queries, which I would like to run from the PHE end in order to provide metadata for samples that are missing the minimal fields. Please enable ouath for these queries. Thanks a lot!

**Comment by SamStudio8** [comment]
Ocarina 0.38.3 now supports `get biosample-validity` with OAuth (https://github.com/SamStudio8/ocarina/commit/fa357872ee1c8bad813956ff8b8b0ea3afa31755)
