### ISSUE TITLE
create an ocarina oauth check command

### ISSUE THREAD

**Issue by fschwach** [COG-UK/dipi-group#66]
For automated processes that call ocarina, it would be useful to have a way of checking that the oauth tokens are up to data. Running the refresh command will block if tokens need refreshing and user input is required, which is not good for unsupervised running of automated commands.
I propose a sub-command
`ocarina oauth check 
`
which could return json with a list of tokens that are up-to-date and a list of tokens that need to be refreshed or an even simpler output that just indicates whether there are any tokens that require refreshing.

**Comment by SamStudio8** [comment]
Bump to #62
