### ISSUE TITLE
add sample collection and received date fields to dataview PHE1 

### ISSUE THREAD

**Issue by fschwach** [COG-UK/dipi-group#69]
I would like to have sample collection and sample received date added to the PHE1 dataview on Majora. This will make it easier for me to use the dates in order to find the correct match of sender sample ID where a barcode has been re-used. This view currently only provides sender_sample_id and central_sample_id fields.

*** 

**Proposed by:** FS (PHEC)
**Approved by:** Health Informatics WG 2020-05-04

**Comment by SamStudio8** [comment]
Approved as discussed at the Health Informatics WG. I suggest we organise an email to users as soon as possible offering 7 days notice of the change to be implemented. We'll then switch on the new fields. In the meantime I'll check what mechanism is in place to update Agreement text.

**Comment by SamStudio8** [comment]
Approved by DWG. We have decided to proceed with facilitating this as the Operational meeting is a week away and this change is a no brainer. I'll alert Slack and get EH to send an email to all sites today, we will implement the change for May 24th.

**Comment by SamStudio8** [comment]
Agreement updated. The system was not designed for unilateral changes, so the version number and date can (and have) been bumped, but the version history is not stored (because it was anticipated that changes would require a new agreement object). For this case I've made it clear what has changed and what has not, as we don't need to overly engineer this!

**Comment by SamStudio8** [comment]
One week on the clock please!

**Comment by SamStudio8** [comment]
MDV has been updated as of now. Ocarina 39.2 is required to correctly unroll the `process` block to get the keys inside. Will liaise with FS now.

**Comment by SamStudio8** [comment]
Spoken to FS and this is all working as planned.
