### ISSUE TITLE
Commas in input metadata

### ISSUE THREAD

**Issue by rmcolq** [COG-UK/dipi-group#72]
While MAJORA metadata is output in TSV format, all of datapipe uses CSV. A comma in user input is currently causing problems downstream. 

- [x] Add something to datapipe to strip commas until a proper fix is decided on (will lead to problems with searching output)
- [x] Check if string parsing splitting by commas is being used
- [x] Check if quotes handled correctly by csv dictreader/fastafunk commands
- [ ] Consider banning commas in input data if it is the only workable solution

**Comment by SamStudio8** [comment]
Eek, the main reason I chose to use TSV is because I'm scared of commas cropping up in code that just splits on delimiter characters. I'd lean towards making the software work on the data rather than the data work for the software. Perhaps we could look at moving some outputs over to TSV before we think about changing the commas themselves.

I guess firstly we should audit the tools that touch the field(s) in question and check they will handle commas appropriately (and what happens if they don't).

**Comment by SamStudio8** [comment]
@rmcolq If commas are stripped by datapipe in downstream metadata (even just temporarily) can we put that in the changelog so we can let users know

**Comment by rmcolq** [comment]
Checking for split(","):
 - [x] geography_cleaning.py
 - [x] Fastafunk
 - [x] Datapipe (is present in a mutations file parser, but not a full metadata table parser)
 - [x] Phylopipe

**Comment by SamStudio8** [comment]
Ocarina has some hard-coded TSV-based outputs, however the code that (can) generate CSV uses Python's `csv.DictWriter` and I've checked this will safely quote the commas without specifying a dialect or anything special. This means the outbound pipelines (eg. GISAID) should be safe from this problem.

**Comment by SamStudio8** [comment]
In a paranoid moment I thought I also better check Nextflow. Nextflow has correctly handled quoted CSV substrings since version 19.04 (https://github.com/nextflow-io/nextflow/blob/master/changelog.txt#L545) - everything on CLIMB-COVID is NF 20 minimum.

**Comment by rmcolq** [comment]
I think it looks like the solution should be quotation marks.

**Comment by SamStudio8** [comment]
In the case of the `root_biosample_id` I am reasonably confident the commas can be stripped safely. A quick check in Majora shows a number of samples with commas in `adm2`, too. So my vote would be for something that can retains commas. If we encounter issues with this downstream (oddly slow parsing or such) then we could swap affected tables to TSV.

**Comment by rmcolq** [comment]
Well this explains a lot: `csv.DictReader` is used to parse the TSV and convert it to a CSV, and it looks like it was already adding quotes where there were commas. I think panic over...
