### ISSUE TITLE
exclude suppressed records from PHE1 dataview

### ISSUE THREAD

**Issue by fschwach** [COG-UK/dipi-group#75]
This has come to light today because a sequencing site had suppressed a record on CLIMB that had insufficient sequence quality but the COG ID to sender sample ID linage is still included in the PHE1 dataview on Majora which leads to the sample (which was wrongly identified as a VUI) being added to reports at PHE.

**Comment by SamStudio8** [comment]
Biosamples are not suppressed, sequences are. The user will need to
either correct or null the `sender_sample_id` for the biosamples in
question.
