### ISSUE TITLE
Allow uploading of samples >1 year old

### ISSUE THREAD

**Issue by martinmchugh** [COG-UK/dipi-group#84]
We are looking out for possible re-infections and may look to sequence old samples stored in the freezer that we didn't have capacity for at the time of collection. These could well be older than 1y but currently these cannot be uploaded to Majora. 

Can this be revisited to remove the block, or an additional metadata flag added to indicate these are definately old samples and not a data entry error?

**Comment by SamStudio8** [comment]
Hi Martin! We did have a proposal to remove the date check entirely which
was rejected by the metadata working group, it's deemed too useful. I think
a flag would be the best way forward and I've previously discussed this
with Anthony too.

We're currently working on scaling solutions and will likely not be able to
do this particularly soon. A rather unpleasant hack to get these samples in
would be to push them with a valid date (ie. not 365 days old), then push
the correct date with Ocarina put biosample --partial, or the uploader - as
we recently added a patch to skip the past date check on samples that
already exist.

I wouldn't want to be seen as recommending this solution but if the samples
are urgent then that would be the way to do it without waiting for us...!

**Comment by rambaut** [comment]
Would it work to put an initial `received_date` in to create the entry and then add the `collection_date` and fix the `received_date`? Might make data integrity a little bit more robust.

**Comment by SamStudio8** [comment]
That's much nicer. I think that should work fine :)

**Comment by SamStudio8** [comment]
Just to be safe, I'd make sure the dates are correct before uploading any
sequences in case they are gobbled up by a pipeline before you get a chance
to fix them!

**Comment by martinmchugh** [comment]
That sounds good, I agree that losing the data check entirely would probably end up letting through many errors in response to reduced effort in a handful of genuine cases. Happy to do the workaround Andrew suggests.

**Comment by SamStudio8** [comment]
Moving this to our backlog (#62) as there is a viable workaround for the moment

**Comment by SamStudio8** [comment]
Majora has been updated to prevent adding or updating any sample from before 2020, https://github.com/SamStudio8/majora/commit/360b0111f9fd71e516f9275a6dfd0c31c3aacd84
